// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/SimulationSession.proto

package org.bluk.physiblox.protos;

public interface CloseSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.CloseSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1[json_name = "uuid"];</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1[json_name = "uuid"];</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
