// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/SimulationSession.proto

package org.bluk.physiblox.protos;

public interface OpenSessionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.OpenSessionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isOpened = 1[json_name = "isOpened"];</code>
   * @return The isOpened.
   */
  boolean getIsOpened();
}
