// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/SimulationRuntime.proto

package org.bluk.physiblox.protos;

public final class SimulationRuntimeProto {
  private SimulationRuntimeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032v1/SimulationRuntime.proto\022\006protos2\023\n\021" +
      "SimulationRuntimeBk\n\031org.bluk.physiblox." +
      "protosB\026SimulationRuntimeProtoP\001\242\002\003PXX\252\002" +
      "\006Protos\312\002\006Protos\342\002\022Protos\\GPBMetadata\352\002\006" +
      "Protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
