// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/SimulationSession.proto

package org.bluk.physiblox.protos;

public final class SimulationSessionProto {
  private SimulationSessionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_OpenSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_OpenSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_OpenSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_OpenSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_CloseSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_CloseSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032v1/SimulationSession.proto\022\006protos\"(\n\022" +
      "OpenSessionRequest\022\022\n\004uuid\030\001 \001(\tR\004uuid\"1" +
      "\n\023OpenSessionResponse\022\032\n\010isOpened\030\001 \001(\010R" +
      "\010isOpened\")\n\023CloseSessionRequest\022\022\n\004uuid" +
      "\030\001 \001(\tR\004uuid\"\007\n\005Empty2\215\001\n\021SimulationSess" +
      "ion\022A\n\004Open\022\032.protos.OpenSessionRequest\032" +
      "\033.protos.OpenSessionResponse\"\000\0225\n\005Close\022" +
      "\033.protos.CloseSessionRequest\032\r.protos.Em" +
      "pty\"\000Bk\n\031org.bluk.physiblox.protosB\026Simu" +
      "lationSessionProtoP\001\242\002\003PXX\252\002\006Protos\312\002\006Pr" +
      "otos\342\002\022Protos\\GPBMetadata\352\002\006Protosb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_OpenSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_OpenSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_OpenSessionRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_protos_OpenSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_OpenSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_OpenSessionResponse_descriptor,
        new java.lang.String[] { "IsOpened", });
    internal_static_protos_CloseSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_CloseSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_CloseSessionRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_protos_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
